# Generated by Django 5.1.7 on 2025-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=100),
        ),
    ]
