# Generated by Django 5.1.7 on 2025-05-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_package_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.CharField(default='Warehouse', max_length=100),
        ),
    ]
